### ISSUE TITLE
Error: cannot activate hypeui This plugin is invalid: This plugin's directory must be renamed to "hypeUI"

### ISSUE THREAD

**Issue by ghost** [hypeJunction/hypeUI#1]
FYI :)
cannot activate
hypeui
This plugin is invalid: This plugin's directory must be renamed to "hypeUI" to match the ID in its manifest.	Location: /var/www/vhosts/beta.socialbusinessworld.org/httpdocs/mod/hypeui/
Check the Elgg documentation for troubleshooting tips.

Screenshots are very nice. Great job!

**Comment by hypeJunction** [comment]
Rename the directory to _hypeui and then hypeUI

**Comment by hypeJunction** [comment]
Refresh the plugins page in between

**Comment by ghost** [comment]
renamed to _hypeui and refreshed, OK
renemed then to hypeUI, refreshed, plugin disappeared from list

**Comment by hypeJunction** [comment]
I am going to fix the composer installer now. Put this in somewhere and run once to delete the plugin instances:
```php
elgg_get_plugin_from_id('hypeui')->delete();
```

**Comment by ghost** [comment]
I ran composer remove hypejunction/hypeui already, will run composer require once fixed hoping it'll be fine :)

**Comment by hypeJunction** [comment]
It's fixed

**Comment by ghost** [comment]
Doesn't work for me, reinstalled but not in plugins' list. I also created a php file with elgg_get_plugin_from_id('hypeui')->delete(); but no results...I guess I am doing something wrong but nevermind, we have more important issues to go through :)
