### ISSUE TITLE
Navigation showing all items

### ISSUE THREAD

**Issue by jeenious** [hypeJunction/hypeUI#3]
I installed the hypeUI into a fresh installation of Elgg and the navigation is showing all items in alphabetical order, rather than the ones that I selected from within "Appearance" --> "Menu Items"

**Comment by hypeJunction** [comment]
Works for me. See if you have third party plugins installed that are altering the site menu.

**Comment by jeenious** [comment]
No, this was a fresh install with no added plugins. I can be contacted via
Skype and share my screen and show you what is happening if you wish, my
skype username is 'jeenious'
ᐧ

**Comment by hypeJunction** [comment]
Install latest dev-master using composer and try again.
