### ISSUE TITLE
Release new version on the Plugins repository

### ISSUE THREAD

**Issue by dploeger** [hypeJunction/hypeUI#31]
I just noticed, that the manifest-file denotes the version as 1.3.1 while the last available version on the official plugin repository is 1.0.0. 

Are there any issues holding you back releasing a new version there?

**Comment by hypeJunction** [comment]
I don't have time to release all ofy plugins on elgg.org. I tried to automate the process, but the core team at the time didn't show enough interest, so that was the end of it. I have too many free plugins to be spending even more free time uploading them to Elgg.org.

**Comment by dploeger** [comment]
Allright. Thanks for the clarification.
