### ISSUE TITLE
Images duplicated in list of groups 

### ISSUE THREAD

**Issue by juniormvs** [hypeJunction/hypeUI#37]
In the list of communities, the avatars are appearing duplicated, please help us. Take a look at the picture bellow.. Thanks. 

P.S. I really appreciate your work

![screenshot-2018-7-9](https://user-images.githubusercontent.com/2208910/42479788-d79a59fc-83b0-11e8-9243-9e89a303b7e7.png)

**Comment by hypeJunction** [comment]
You may need to remove the icon from them overriding view, I suppose you use some custom group addon

**Comment by dploeger** [comment]
I have the same on my site. I'm not completely sure, from where it's coming, but we fixed it with [some custom css](https://github.com/wabuehamm/elgg-plugin-wabue/blob/master/views/default/css/hypefixes.css#L7)

**Comment by juniormvs** [comment]
I really appreciate your help guys, the issue is because I was using the **group tools** combined with the plugin **group**, so I disable the plugin group tools, and the duplicate image disappeared. 

I really appreciate your time spent to help me, 

Regards..

Mário Jr.

**Comment by dploeger** [comment]
I don't use that plugin. So it's something different on my site. But I have a solution with the CSS. So, I'm not simply reopening it.
